# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/2019spring/codex/draw/draw.cache/wt [current_project]
set_property parent.project_path F:/2019spring/codex/draw/draw.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet F:/2019spring/codex/draw/draw.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files F:/2019spring/codex/draw/draw.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet F:/2019spring/codex/draw/draw.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files F:/2019spring/codex/draw/draw.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib F:/2019spring/codex/draw/draw.srcs/sources_1/new/pcu.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/2019spring/codex/draw/draw.srcs/constrs_1/imports/Verilog/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files F:/2019spring/codex/draw/draw.srcs/constrs_1/imports/Verilog/Nexys4DDR_Master.xdc]


synth_design -top pcu -part xc7a100tcsg324-1


write_checkpoint -force -noxdef pcu.dcp

catch { report_utilization -file pcu_utilization_synth.rpt -pb pcu_utilization_synth.pb }
