# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/2019spring/codex/lab3_3/lab3_3.cache/wt [current_project]
set_property parent.project_path F:/2019spring/codex/lab3_3/lab3_3.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet F:/2019spring/codex/lab3_3/lab3_3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/2019spring/codex/lab3_3/lab3_3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/2019spring/codex/lab3_3/lab3_3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/2019spring/codex/lab3_3/lab3_3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files F:/2019spring/codex/lab3_3/lab3_3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

read_verilog -library xil_defaultlib F:/2019spring/codex/lab3_3/lab3_3.srcs/sources_1/new/fifo.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/2019spring/codex/lab3_3/lab3_3.srcs/constrs_1/imports/tutorial/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files F:/2019spring/codex/lab3_3/lab3_3.srcs/constrs_1/imports/tutorial/Nexys4DDR_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top fifo -part xc7a100tcsg324-1


write_checkpoint -force -noxdef fifo.dcp

catch { report_utilization -file fifo_utilization_synth.rpt -pb fifo_utilization_synth.pb }
